<template>
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="
      margin: auto;
      background: none;
      display: block;
      shape-rendering: auto;
    "
    width="201px"
    height="201px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <circle cx="84" cy="50" r="10" fill="#7b7373">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="0.5555555555555556s"
        calcMode="spline"
        keyTimes="0;1"
        values="9;0"
        keySplines="0 0.5 0.5 1"
        begin="0s"
      ></animate>
      <animate
        attributeName="fill"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="discrete"
        keyTimes="0;0.25;0.5;0.75;1"
        values="#7b7373;#b7bbd0;#d0b7b7;#9a82c8;#7b7373"
        begin="0s"
      ></animate>
    </circle>
    <circle cx="16" cy="50" r="10" fill="#7b7373">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="0s"
      ></animate>
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="0s"
      ></animate>
    </circle>
    <circle cx="50" cy="50" r="10" fill="#9a82c8">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.5555555555555556s"
      ></animate>
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-0.5555555555555556s"
      ></animate>
    </circle>
    <circle cx="84" cy="50" r="10" fill="#d0b7b7">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-1.1111111111111112s"
      ></animate>
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-1.1111111111111112s"
      ></animate>
    </circle>
    <circle cx="16" cy="50" r="10" fill="#b7bbd0">
      <animate
        attributeName="r"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="0;0;9;9;9"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-1.6666666666666665s"
      ></animate>
      <animate
        attributeName="cx"
        repeatCount="indefinite"
        dur="2.2222222222222223s"
        calcMode="spline"
        keyTimes="0;0.25;0.5;0.75;1"
        values="16;16;16;50;84"
        keySplines="0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1;0 0.5 0.5 1"
        begin="-1.6666666666666665s"
      ></animate>
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
</template>
